### ISSUE TITLE
UTF8 issue?

### ISSUE THREAD

**Issue by DanielFragaBR** [lavv17/le#12]
Sometimes I edit a file with chars with accents like Ç, é, á, ú etc and I notice that if these chars are the last one in line, le editor gets confused and strips them out.

I'm using the last version (1.15.1). Any hints?

**Comment by lavv17** [comment]
Can you send me a sample of such a file?

**Comment by DanielFragaBR** [comment]
Sure, but for some reason I can't attach it here (github returns error). Try to download from there:

https://mega.nz/#!RQoWWJTA!plY_-rlqPSg8MWsGGvi5rdP1mNZObGMyIAtRJhqpKG4

The contents of the file should be: 

Conta POUPANÇA

but it saves as:

Conta POUPAN�A

I think there's a confusion between ISO-8859-1 and UTF8...

**Comment by DanielFragaBR** [comment]
When I insert the "Ç" file, it jumps 2 chars ahead... it's strange.

**Comment by lavv17** [comment]
I think it's a problem with your system libraries. What kind of unix do you
use?
On my linux (fedora 20) the text "Conta POUPANÇA" is entered and saved with
no problems.


2015-10-12 23:07 GMT+03:00 Dâniel Fraga <notifications@github.com>:

> When I insert the "Ç" file, it jumps 2 chars ahead... it's strange.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavv17/le/issues/12#issuecomment-147505783>.
>



-- 
   Alexander.

**Comment by DanielFragaBR** [comment]
My installation is like Linux from scratch. The strange is that it only happens with "le". The others editors like vi, jed etc are fine. Any library I should look more to solve this? Any hints?

**Comment by lavv17** [comment]
LE uses system function mbtowc which is defined by glibc. Glibc itself uses
locale files. You can check current locale by running "locale" command.

2015-10-13 16:28 GMT+03:00 Dâniel Fraga <notifications@github.com>:

> My installation is like Linux from scratch. The strange is that it only
> happens with "le". The others editors like vi, jed etc are fine. Any
> library I should look more to solve this? Any hints?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavv17/le/issues/12#issuecomment-147714373>.
>



-- 
   Alexander.

**Comment by DanielFragaBR** [comment]
My locale seems fine:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Any more hints?

**Comment by lavv17** [comment]
Try to download and open http://lav.yar.ru/UTF-8-demo.txt, see what's
displayed on your terminal.

2015-10-16 20:03 GMT+03:00 Dâniel Fraga <notifications@github.com>:

> My locale seems fine:
>
> LANG=en_US.UTF-8
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_US.UTF-8"
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER="en_US.UTF-8"
> LC_NAME="en_US.UTF-8"
> LC_ADDRESS="en_US.UTF-8"
> LC_TELEPHONE="en_US.UTF-8"
> LC_MEASUREMENT="en_US.UTF-8"
> LC_IDENTIFICATION="en_US.UTF-8"
> LC_ALL=
>
> Any more hints?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavv17/le/issues/12#issuecomment-148773273>.
>



-- 
   Alexander.

**Comment by DanielFragaBR** [comment]
It seems fine here. I attached the screenshots so you can confirm.
![le1](https://cloud.githubusercontent.com/assets/6537729/10548808/a2244440-7413-11e5-9967-c364f0586181.png)
![le2](https://cloud.githubusercontent.com/assets/6537729/10548811/a7f52a42-7413-11e5-8e12-4f2b3887fd93.png)
![le3](https://cloud.githubusercontent.com/assets/6537729/10548816/ab5f4f50-7413-11e5-891a-56030bffe1bd.png)
![le4](https://cloud.githubusercontent.com/assets/6537729/10548818/ade42098-7413-11e5-892e-7f6e9e74bc04.png)

**Comment by lavv17** [comment]
It's not quite fine. Probably wcwidth function is broken in some way.
Please check ncursesw version and see config.log of LE for wcwith checking.
Here I use glibc-2.20 and ncurses-5.9, configure accepts glibc built-in
wcwidth function.

2015-10-16 20:39 GMT+03:00 Dâniel Fraga <notifications@github.com>:

> It seems fine here. I attached the screenshots so you can confirm.
> [image: le1]
> <https://cloud.githubusercontent.com/assets/6537729/10548808/a2244440-7413-11e5-9967-c364f0586181.png>
> [image: le2]
> <https://cloud.githubusercontent.com/assets/6537729/10548811/a7f52a42-7413-11e5-8e12-4f2b3887fd93.png>
> [image: le3]
> <https://cloud.githubusercontent.com/assets/6537729/10548816/ab5f4f50-7413-11e5-891a-56030bffe1bd.png>
> [image: le4]
> <https://cloud.githubusercontent.com/assets/6537729/10548818/ade42098-7413-11e5-892e-7f6e9e74bc04.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavv17/le/issues/12#issuecomment-148781333>.
>



-- 
   Alexander.

**Comment by DanielFragaBR** [comment]
You're right! It was an issue with ncurses. I updated it and now it's perfect. 

Thank you very much!
