### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by stefanhusmann** [lavv17/le#14]
The last commit brought up the following build problem: 
gcc -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../lib  -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -MT block.o -MD -MP -MF .deps/block.Tpo -c -o block.o block.cc
In file included from block.cc:35:0:
keymap.h:22:25: fatal error: action-enum.h: No such file or directory
compilation terminated.
Makefile:1294: recipe for target 'block.o' failed
make[1]: *** [block.o] Error 1
make[1]: Leaving directory '/home/haawda/paketierung/meine_Pakete/le-editor-git/src/le-editor/src'
Makefile:1168: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by stefanhusmann** [comment]
action-enum.h is indeed missing.

**Comment by stefanhusmann** [comment]
In commit 614, the message changed to 
gcc -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../lib  -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -MT loadsave.o -MD -MP -MF .deps/loadsave.Tpo -c -o loadsave.o loadsave.cc
loadsave.cc: In function 'int SaveFile(char*)':
loadsave.cc:678:22: warning: ignoring return value of 'int ftruncate(int, __off_t)', declared with attribute warn_unused_result [-Wunused-result]
    ftruncate(nfile,0);
                      ^
mv -f .deps/loadsave.Tpo .deps/loadsave.Po
make[1]: *** No rule to make target 'make-mainmenu.pl', needed by 'mainmenu-default.h'.  Stop.
make[1]: Leaving directory '/home/haawda/paketierung/meine_Pakete/le-editor-git/src/le-editor/src'
Makefile:1168: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

and indeed make-mainmenu.pl is missing.

**Comment by stefanhusmann** [comment]
thanks, all fixed.

**Comment by lavv17** [comment]
Thanks for comments! It's definitely a problem that I don't have an on-commit compile check.
