### ISSUE TITLE
Add "default EOL" option.

### ISSUE THREAD

**Issue by gene-pavlovsky** [lavv17/le#15]
I use Cygwin so `le` creates new files with DOS EOLs by default. This behavior is decided at compile time in loadsave.cc.
I use `le` to edit shell scripts when I'm working in Cygwin, bash can't handle DOS EOLs, so any time I create a new shell script with `le`, I have to convert the line endings later.
Most text editors I know offer an option to choose the default EOL. Please add an option like this.
For now I have to remove the appropriate `ifdef` in `loadsave.cc` and recompile, to get the desired UNIX EOLs.

**Comment by lavv17** [comment]
should be fixed in 275a4c3 (see LE_DEFAULT_EOL environment variable).

**Comment by gene-pavlovsky** [comment]
Thanks. How about also adding a compile time option to `configure`?
