### ISSUE TITLE
Build fails on recent macOS

### ISSUE THREAD

**Issue by fxcoudert** [lavv17/le#27]
The last two major versions of macOS cannot build le anymore, because the le configure hardcodes the possible paths for ncurses, and does not find the curses headers and library, even though they are present on macOS.

Recent macOS versions don't put headers in `/usr/include` anymore, but in places  that depend on the SDK being targeted  (paths like `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/ncurses.h`).

Please add a `configure` option so the curses path can be provided.

**Comment by lavv17** [comment]
With this change d921a3cdb3e1a0b50624d17e5efeb5a76d64f29d the configure options --with-curses-lib and --with-curses-include can be used to specify a custom location. Please try.
